use crate::types::*;

pub fn sorting_entries() -> Vec<AlgorithmEntry> {
    vec![
        AlgorithmEntry { algorithm: "selection-sort".into(),
            meta: meta_full!("selection-sort","选择排序","Selection Sort",Sorting,"每轮从未排序区间选出最小元素放到已排序区间末尾。",time="O(n²)",best="O(n²)",avg="O(n²)",worst="O(n²)",space="O(1)",stable="不稳定",use=["数据量小","内存受限"]),
            samples: CodeSamples {
                cpp: cpp!("void selectionSort(vector<int>& arr) {","  int n = arr.size();","  for (int i = 0; i < n; i++) {","    int minIdx = i;","    for (int j = i + 1; j < n; j++) {","      if (arr[j] < arr[minIdx]) {","        minIdx = j;","      }","    }","    if (minIdx != i) {","      swap(arr[i], arr[minIdx]);","    }","  }","}"),
                python: py!("def selection_sort(arr):","    n = len(arr)","    for i in range(n):","        min_idx = i","        for j in range(i + 1, n):","            if arr[j] < arr[min_idx]:","                min_idx = j","        if min_idx != i:","            arr[i], arr[min_idx] = arr[min_idx], arr[i]"),
                rust: rs!("fn selection_sort(arr: &mut [i32]) {","    let n = arr.len();","    for i in 0..n {","        let mut min_idx = i;","        for j in (i + 1)..n {","            if arr[j] < arr[min_idx] {","                min_idx = j;","            }","        }","        if min_idx != i {","            arr.swap(i, min_idx);","        }","    }","}"),
            },
            line_map: lm!("outer"=>[3],"select-min"=>[4],"compare"=>[6],"update-min"=>[7],"swap"=>[10],"done"=>[13]),
        },
        AlgorithmEntry { algorithm: "bubble-sort".into(),
            meta: meta_full!("bubble-sort","冒泡排序","Bubble Sort",Sorting,"相邻元素比较并交换，使较大元素逐渐冒泡到末尾。",time="O(n²)",best="O(n)",avg="O(n²)",worst="O(n²)",space="O(1)",stable="稳定",use=["教学演示","基本有序"]),
            samples: CodeSamples {
                cpp: cpp!("void bubbleSort(vector<int>& arr) {","  int n = arr.size();","  for (int i = 0; i < n; i++) {","    for (int j = 0; j < n - i - 1; j++) {","      if (arr[j] > arr[j + 1]) {","        swap(arr[j], arr[j + 1]);","      }","    }","  }","}"),
                python: py!("def bubble_sort(arr):","    n = len(arr)","    for i in range(n):","        for j in range(n - i - 1):","            if arr[j] > arr[j + 1]:","                arr[j], arr[j + 1] = arr[j + 1], arr[j]"),
                rust: rs!("fn bubble_sort(arr: &mut [i32]) {","    let n = arr.len();","    for i in 0..n {","        for j in 0..(n - i - 1) {","            if arr[j] > arr[j + 1] {","                arr.swap(j, j + 1);","            }","        }","    }","}"),
            },
            line_map: lm!("outer"=>[3],"compare"=>[5],"swap"=>[6],"done"=>[10]),
        },
        AlgorithmEntry { algorithm: "insertion-sort".into(),
            meta: meta_full!("insertion-sort","插入排序","Insertion Sort",Sorting,"将元素逐个插入到已排序序列的合适位置。",time="O(n²)",best="O(n)",avg="O(n²)",worst="O(n²)",space="O(1)",stable="稳定",use=["小规模","部分有序"]),
            samples: CodeSamples {
                cpp: cpp!("void insertionSort(vector<int>& arr) {","  int n = arr.size();","  for (int i = 1; i < n; i++) {","    int key = arr[i];","    int j = i - 1;","    while (j >= 0 && arr[j] > key) {","      arr[j + 1] = arr[j];","      j--;","    }","    arr[j + 1] = key;","  }","}"),
                python: py!("def insertion_sort(arr):","    for i in range(1, len(arr)):","        key = arr[i]","        j = i - 1","        while j >= 0 and arr[j] > key:","            arr[j + 1] = arr[j]","            j -= 1","        arr[j + 1] = key"),
                rust: rs!("fn insertion_sort(arr: &mut [i32]) {","    for i in 1..arr.len() {","        let key = arr[i];","        let mut j = i;","        while j > 0 && arr[j - 1] > key {","            arr[j] = arr[j - 1];","            j -= 1;","        }","        arr[j] = key;","    }","}"),
            },
            line_map: lm!("outer"=>[3],"compare"=>[6],"shift"=>[7],"insert"=>[10],"done"=>[12]),
        },
        AlgorithmEntry { algorithm: "merge-sort".into(),
            meta: meta_full!("merge-sort","归并排序","Merge Sort",Sorting,"分治法拆分排序后合并，稳定且可预测。",time="O(n log n)",best="O(n log n)",avg="O(n log n)",worst="O(n log n)",space="O(n)",stable="稳定",use=["链表排序","外部排序","需稳定排序"]),
            samples: CodeSamples {
                cpp: cpp!("void mergeSort(vector<int>& arr, int l, int r) {","  if (l >= r) return;","  int m = l + (r - l) / 2;","  mergeSort(arr, l, m);","  mergeSort(arr, m + 1, r);","  merge(arr, l, m, r);","}","void merge(vector<int>& arr, int l, int m, int r) {","  vector<int> temp(arr.begin() + l, arr.begin() + r + 1);","  int i = 0, j = m - l + 1, k = l;","  while (i <= m - l && j <= r - l) {","    if (temp[i] <= temp[j]) {","      arr[k++] = temp[i++];","    } else {","      arr[k++] = temp[j++];","    }","  }","  while (i <= m - l) arr[k++] = temp[i++];","  while (j <= r - l) arr[k++] = temp[j++];","}"),
                python: py!("def merge_sort(arr, l, r):","    if l >= r:","        return","    m = (l + r) // 2","    merge_sort(arr, l, m)","    merge_sort(arr, m + 1, r)","    merge(arr, l, m, r)","","def merge(arr, l, m, r):","    temp = arr[l:r + 1]","    i, j, k = 0, m - l + 1, l","    while i <= m - l and j <= r - l:","        if temp[i] <= temp[j]:","            arr[k] = temp[i]","            i += 1","        else:","            arr[k] = temp[j]","            j += 1","        k += 1","    while i <= m - l:","        arr[k] = temp[i]","        i += 1","        k += 1","    while j <= r - l:","        arr[k] = temp[j]","        j += 1","        k += 1"),
                rust: rs!("fn merge_sort(arr: &mut [i32]) {","    if arr.len() <= 1 { return; }","    let mid = arr.len() / 2;","    let (left, right) = arr.split_at_mut(mid);","    merge_sort(left);","    merge_sort(right);","    merge(arr);","}","fn merge(arr: &mut [i32]) {","    let mid = arr.len() / 2;","    let mut temp = arr.to_vec();","    let (l, r) = temp.split_at(mid);","    let mut i = 0; let mut j = 0; let mut k = 0;","    while i < l.len() && j < r.len() {","        if l[i] <= r[j] {","            arr[k] = l[i]; i += 1;","        } else {","            arr[k] = r[j]; j += 1;","        }","        k += 1;","    }","    while i < l.len() { arr[k] = l[i]; i += 1; k += 1; }","    while j < r.len() { arr[k] = r[j]; j += 1; k += 1; }","}"),
            },
            line_map: lm!("merge-sort"=>[1],"compare"=>[14],"write-left"=>[15],"write-right"=>[17],"done"=>[9]),
        },
        AlgorithmEntry { algorithm: "quick-sort".into(),
            meta: meta_full!("quick-sort","快速排序","Quick Sort",Sorting,"选择枢轴划分子区间并递归排序。",time="O(n log n)",best="O(n log n)",avg="O(n log n)",worst="O(n²)",space="O(log n)",stable="不稳定",use=["大规模","通用排序"]),
            samples: CodeSamples {
                cpp: cpp!("void quickSort(vector<int>& arr, int low, int high) {","  if (low < high) {","    int pi = partition(arr, low, high);","    quickSort(arr, low, pi - 1);","    quickSort(arr, pi + 1, high);","  }","}","int partition(vector<int>& arr, int low, int high) {","  int pivot = arr[high];","  int i = low;","  for (int j = low; j < high; j++) {","    if (arr[j] <= pivot) {","      swap(arr[i], arr[j]);","      i++;","    }","  }","  swap(arr[i], arr[high]);","  return i;","}"),
                python: py!("def quick_sort(arr, low, high):","    if low < high:","        pi = partition(arr, low, high)","        quick_sort(arr, low, pi - 1)","        quick_sort(arr, pi + 1, high)","","def partition(arr, low, high):","    pivot = arr[high]","    i = low","    for j in range(low, high):","        if arr[j] <= pivot:","            arr[i], arr[j] = arr[j], arr[i]","            i += 1","    arr[i], arr[high] = arr[high], arr[i]","    return i"),
                rust: rs!("fn quick_sort(arr: &mut [i32]) {","    if arr.len() > 1 {","        let p = partition(arr);","        let (left, right) = arr.split_at_mut(p);","        quick_sort(left);","        quick_sort(&mut right[1..]);","    }","}","fn partition(arr: &mut [i32]) -> usize {","    let hi = arr.len() - 1;","    let mut i = 0;","    for j in 0..hi {","        if arr[j] <= arr[hi] {","            arr.swap(i, j);","            i += 1;","        }","    }","    arr.swap(i, hi);","    i","}"),
            },
            line_map: lm!("quick-sort"=>[1],"compare"=>[12],"swap"=>[13],"pivot-swap"=>[17],"done"=>[7]),
        },
        AlgorithmEntry { algorithm: "heap-sort".into(),
            meta: meta_full!("heap-sort","堆排序","Heap Sort",Sorting,"构建最大堆后不断取出堆顶完成排序。",time="O(n log n)",best="O(n log n)",avg="O(n log n)",worst="O(n log n)",space="O(1)",stable="不稳定",use=["Top K","内存受限"]),
            samples: CodeSamples {
                cpp: cpp!("void heapify(vector<int>& arr, int n, int i) {","  int largest = i, l = 2*i+1, r = 2*i+2;","  if (l < n && arr[l] > arr[largest]) largest = l;","  if (r < n && arr[r] > arr[largest]) largest = r;","  if (largest != i) { swap(arr[i], arr[largest]);","    heapify(arr, n, largest); }","}","void heapSort(vector<int>& arr) {","  int n = arr.size();","  for (int i = n/2-1; i >= 0; i--) heapify(arr,n,i);","  for (int i = n-1; i > 0; i--) {","    swap(arr[0], arr[i]);","    heapify(arr, i, 0);","  }","}"),
                python: py!("def heapify(arr, n, i):","    largest, l, r = i, 2*i+1, 2*i+2","    if l < n and arr[l] > arr[largest]: largest = l","    if r < n and arr[r] > arr[largest]: largest = r","    if largest != i:","        arr[i], arr[largest] = arr[largest], arr[i]","        heapify(arr, n, largest)","def heap_sort(arr):","    n = len(arr)","    for i in range(n//2-1, -1, -1): heapify(arr,n,i)","    for i in range(n-1, 0, -1):","        arr[0], arr[i] = arr[i], arr[0]","        heapify(arr, i, 0)"),
                rust: rs!("fn heapify(arr: &mut [i32], n: usize, i: usize) {","    let mut largest = i;","    let (l, r) = (2*i+1, 2*i+2);","    if l < n && arr[l] > arr[largest] { largest = l; }","    if r < n && arr[r] > arr[largest] { largest = r; }","    if largest != i { arr.swap(i, largest);","      heapify(arr, n, largest); }","}","fn heap_sort(arr: &mut [i32]) {","    let n = arr.len();","    for i in (0..n/2).rev() { heapify(arr,n,i); }","    for i in (1..n).rev() {","        arr.swap(0, i);","        heapify(arr, i, 0);","    }","}"),
            },
            line_map: lm!("heap-sort"=>[9],"compare"=>[2],"extract-max"=>[12],"heapify"=>[3],"sink"=>[5],"done"=>[15]),
        },
        AlgorithmEntry { algorithm: "shell-sort".into(),
            meta: meta_full!("shell-sort","希尔排序","Shell Sort",Sorting,"改进的插入排序，通过递减增量分组排序逐步逼近有序。",time="O(n log² n)",best="O(n log n)",avg="O(n log² n)",worst="O(n²)",space="O(1)",stable="不稳定",use=["中等规模","插入排序的改进替代"]),
            samples: CodeSamples {
                cpp: cpp!("void shellSort(vector<int>& arr) {","  int n = arr.size();","  for (int gap = n / 2; gap > 0; gap /= 2) {","    for (int i = gap; i < n; i++) {","      int temp = arr[i];","      int j = i;","      while (j >= gap && arr[j - gap] > temp) {","        arr[j] = arr[j - gap];","        j -= gap;","      }","      arr[j] = temp;","    }","  }","}"),
                python: py!("def shell_sort(arr):","    n = len(arr)","    gap = n // 2","    while gap > 0:","        for i in range(gap, n):","            temp = arr[i]","            j = i","            while j >= gap and arr[j - gap] > temp:","                arr[j] = arr[j - gap]","                j -= gap","            arr[j] = temp","        gap //= 2"),
                rust: rs!("fn shell_sort(arr: &mut [i32]) {","    let n = arr.len();","    let mut gap = n / 2;","    while gap > 0 {","        for i in gap..n {","            let temp = arr[i];","            let mut j = i;","            while j >= gap && arr[j - gap] > temp {","                arr[j] = arr[j - gap];","                j -= gap;","            }","            arr[j] = temp;","        }","        gap /= 2;","    }","}"),
            },
            line_map: lm!("shell-sort"=>[1],"gap"=>[3],"select-key"=>[6],"compare"=>[8],"shift"=>[9],"insert"=>[12],"done"=>[14]),
        },
        AlgorithmEntry { algorithm: "counting-sort".into(),
            meta: meta_simple!("counting-sort","计数排序","Counting Sort",Sorting,"统计每个值出现的次数，通过前缀和确定位置。",time="O(n+k)",space="O(k)",use=["整数排序","值域较小"]),
            samples: CodeSamples {
                cpp: cpp!("void countingSort(vector<int>& arr) {","  int maxV = *max_element(arr.begin(),arr.end());","  int minV = *min_element(arr.begin(),arr.end());","  int range = maxV - minV + 1;","  vector<int> count(range), output(arr.size());","  for (int v : arr) count[v - minV]++;","  for (int i = 1; i < range; i++) count[i] += count[i-1];","  for (int i = arr.size()-1; i >= 0; i--) {","    output[count[arr[i]-minV]-1] = arr[i];","    count[arr[i]-minV]--;","  }","  arr = output;","}"),
                python: py!("def counting_sort(arr):","    max_v, min_v = max(arr), min(arr)","    range_v = max_v - min_v + 1","    count = [0] * range_v","    output = [0] * len(arr)","    for v in arr: count[v - min_v] += 1","    for i in range(1, range_v): count[i] += count[i-1]","    for v in reversed(arr):","        output[count[v-min_v]-1] = v","        count[v-min_v] -= 1","    return output"),
                rust: rs!("fn counting_sort(arr: &mut [i32]) {","    let max_v = *arr.iter().max().unwrap_or(&0);","    let min_v = *arr.iter().min().unwrap_or(&0);","    let range = (max_v - min_v + 1) as usize;","    let mut count = vec![0; range];","    let mut output = vec![0; arr.len()];","    for &v in arr.iter() { count[(v-min_v) as usize] += 1; }","    for i in 1..range { count[i] += count[i-1]; }","    for &v in arr.iter().rev() {","        let idx = (v - min_v) as usize;","        count[idx] -= 1;","        output[count[idx]] = v;","    }","    arr.clone_from_slice(&output);","}"),
            },
            line_map: lm!("counting-sort"=>[1],"find-range"=>[4],"count"=>[6],"prefix-sum"=>[7],"place"=>[9],"done"=>[14]),
        },
        AlgorithmEntry { algorithm: "bucket-sort".into(),
            meta: meta_simple!("bucket-sort","桶排序","Bucket Sort",Sorting,"将元素分配到多个桶中，桶内排序后合并。",time="O(n+k)",space="O(n+k)",use=["均匀分布数据","外部排序"]),
            samples: CodeSamples {
                cpp: cpp!("void bucketSort(vector<int>& arr) {","  int n = arr.size(), maxV=*max_element(arr.begin(),arr.end());","  int minV=*min_element(arr.begin(),arr.end());","  int k = sqrt(n);","  vector<vector<int>> buckets(k);","  for (int v : arr) {","    int idx = (v-minV)*(k-1)/(maxV-minV+1);","    buckets[idx].push_back(v);","  }","  int p = 0;","  for (auto& b : buckets) {","    sort(b.begin(), b.end());","    for (int v : b) arr[p++] = v;","  }","}"),
                python: py!("def bucket_sort(arr):","    n = len(arr)","    k = int(n ** 0.5)","    max_v, min_v = max(arr), min(arr)","    buckets = [[] for _ in range(k)]","    for v in arr:","        idx = (v-min_v)*(k-1)//(max_v-min_v+1)","        buckets[idx].append(v)","    arr.clear()","    for b in buckets:","        b.sort()","        arr.extend(b)"),
                rust: rs!("fn bucket_sort(arr: &mut [i32]) {","    let n = arr.len();","    let max_v = *arr.iter().max().unwrap_or(&0);","    let min_v = *arr.iter().min().unwrap_or(&0);","    let k = (n as f64).sqrt() as usize;","    let mut buckets: Vec<Vec<i32>> = vec![vec![]; k];","    for &v in arr.iter() {","        let idx = ((v-min_v)*(k as i32 -1)/(max_v-min_v+1).max(1)) as usize;","        buckets[idx.min(k-1)].push(v);","    }","    let mut p = 0;","    for b in buckets.iter_mut() { b.sort(); for &v in b.iter() { arr[p]=v; p+=1; } }","}"),
            },
            line_map: lm!("bucket-sort"=>[1],"create-buckets"=>[5],"distribute"=>[8],"sort-bucket"=>[12],"done"=>[13]),
        },
        AlgorithmEntry { algorithm: "radix-sort".into(),
            meta: meta_simple!("radix-sort","基数排序","Radix Sort",Sorting,"按位排序，从低位到高位依次进行稳定计数排序。",time="O(d·(n+k))",space="O(n+k)",use=["整数排序","字符串排序"]),
            samples: CodeSamples {
                cpp: cpp!("void radixSort(vector<int>& arr) {","  int maxV = *max_element(arr.begin(),arr.end());","  for (int exp = 1; maxV/exp > 0; exp *= 10) {","    vector<int> output(arr.size());","    int count[10] = {0};","    for (int v : arr) count[(v/exp)%10]++;","    for (int i = 1; i < 10; i++) count[i] += count[i-1];","    for (int i = arr.size()-1; i >= 0; i--) {","      output[count[(arr[i]/exp)%10]-1] = arr[i];","      count[(arr[i]/exp)%10]--;","    }","    arr = output;","  }","}"),
                python: py!("def radix_sort(arr):","    max_v = max(arr)","    exp = 1","    while max_v // exp > 0:","        output = [0] * len(arr)","        count = [0] * 10","        for v in arr: count[(v//exp)%10] += 1","        for i in range(1,10): count[i] += count[i-1]","        for v in reversed(arr):","            count[(v//exp)%10] -= 1","            output[count[(v//exp)%10]] = v","        arr[:] = output","        exp *= 10"),
                rust: rs!("fn radix_sort(arr: &mut [i32]) {","    let max_v = *arr.iter().max().unwrap_or(&0);","    let mut exp = 1;","    let mut output = vec![0; arr.len()];","    while max_v / exp > 0 {","        let mut count = [0usize; 10];","        for &v in arr.iter() { count[((v/exp)%10) as usize] += 1; }","        for i in 1..10 { count[i] += count[i-1]; }","        for &v in arr.iter().rev() {","            let d = ((v/exp)%10) as usize; count[d] -= 1;","            output[count[d]] = v;","        }","        arr.clone_from_slice(&output);","        exp *= 10;","    }","}"),
            },
            line_map: lm!("radix-sort"=>[1],"digit"=>[4],"place"=>[11],"done"=>[16]),
        },
    ]
}
